#!/bin/bash

not_a_godot_project () {
  echo
  echo "Please move to the appropriate directory and run this script again."
  echo
  exit 1
}

validate_project_dir () {
  if [ ! -f project.godot ]; then
    not_a_godot_project
  fi
}

create_addons_dirs () {
  mkdir -p addons
  echo "Addons directory created"
}

create_assets_dirs () {
  # Audio
  mkdir -p assets/audio/sounds_effects assets/audio/music
  # Art
  mkdir -p assets/art/sprites assets/art/spritesheets assets/art/textures assets/art/tilesets
  echo "Assets directory and sub-directories created"
}

create_scenes_dirs () {
  # Charactor Scenes
  mkdir -p scenes/characters/enemies scenes/characters/bosses scenes/characters/npcs
  # Other Scenes
  mkdir -p scenes/components scenes/effects scenes/items scenes/levels scenes/weapons scenes/world_objects
  echo "Scenes directory and sub-directories created"
}

create_scripts_dirs () {
  mkdir -p scripts/autoloads
  echo "Scripts directory and sub-directories created"
}

## Execution Chain
echo # Padding from previous terminal executions
validate_project_dir

# Create Directories
create_addons_dirs
create_assets_dirs
create_scenes_dirs
create_scripts_dirs

echo "Done creating Godot project directory structure."
